version: "3.8"

services:

  db_postgres:
    image: postgres:13.2
    restart: always
    env_file:
      - flaskr/env/.env_flask.list
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  flask_app:
    build: flaskr/
    restart: on-failure
    env_file:
      - flaskr/env/.env_flask.list
    ports:
      - "8000:8000"
    depends_on:
      - "db_postgres"

  nginx:
    image: nginx
    depends_on:
      - "flask_app"
    ports:
      - "80:80"
    volumes:
      - ./flaskr/nginx:/etc/nginx/conf.d




volumes:

  db-data:

