version: "3.8"

services:

  db_postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  flask_app:
    build: flaskr/
    restart: on-failure
    command: sh -c 'while ! nc -z db_postgres 5432; do sleep 1; done;  gunicorn --bind 0.0.0.0:8000 flaskr.main:app'
    environment:
      - FLASK_APP=main
      - FLASK_ENV=development
      - PYTHONPATH=/
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres

  nginx:
    image: nginx
    depends_on:
      - "flask_app"
    ports:
      - "80:80"
    volumes:
      - ./flaskr/nginx:/etc/nginx/conf.d


volumes:

  dbdata:

